### ISSUE TITLE
Recommended use pre-commit to make code style consistency

### ISSUE THREAD

**Issue by luxiaba** [lobbyboy-ssh/lobbyboy#48]
@laixintao @messense @frostming 

Recommended use [pre-commit](https://pre-commit.com/) to make code style consistency, especially in the case of multi-person cooperation, what do you think?

**Comment by frostming** [comment]
+1 for me, I am using pre-commit and pre-commit-ci for most of my projects.

**Comment by laixintao** [comment]
+1

**Comment by luxiaba** [comment]
closed this in #57
